<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
<h1>¿Qué te ofrecemos en TindWare?</h1>
<p></p>
<h1>¿Por que es importante hacer revisiones de los dispositivos informaticos?</h1>
<p></p>
<h1>¿Cuanto es el tiempo de respuesta a una consulta?</h1>
<p></p>
<h1>¿Hay que pagar mensualidades?</h1>
<p></p>
<h1>¿Comó es el proceso de contratación?</h1>
<p></p>
<h1>¿Porque tenemos que registar vuestra ubicacion?</h1>
<p> Si habilitas la ubicación precisa, podremos tener a tiempo completo la ubicacion
 y usar tu ubicación precisa, como la información del GPS</p>

 
 </p>   
</body>
</html>