<!DOCTYPE html>
<html lang="en">
<head>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-M2KBL8D');</script>
<!-- End Google Tag Manager -->
</head>
<body>
   <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M2KBL8D"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) --> 
<h1>¿Qué te ofrecemos en TindWare?</h1>
<p></p>

<h1>¿Por que es importante hacer revisiones de los dispositivos informaticos?</h1>
<p>Al igual que cualquier dispositivo o herramienta de uso cotidiano, los aparatos informaticos
necesitas de un mantenimiento cada un intervalo de tiempo. De esta manera podremos alargar la 
vida de todos los dispositivos</p>

<h1>¿Cuanto es el tiempo de respuesta a una consulta?</h1>
<p>Tratamos siempre de proporcionar ayuda en el menor tiempo posible, sea el problema que sea. Lo unico que no podemos
controlar es la cantidad de consultas que podamos llegar a tener al momento, por lo que el tiempo dependera de ello.</p>

<h1>¿Hay que pagar mensualidades?</h1>
<p>No, </p>

<h1>¿Comó es el proceso de contratación?</h1>
<p>Despues de registrarse en la pagina web, el solicitante puede depositar su curriculum en el apartado correspondiente 
y despues de ello uno de nuestros gestores pasara a examinarlo. En caso de querer contar con su ayuda dicho gestor se 
pondra en contacto con usted en 48-72h</p>

<h1>¿</h1>
<p></p>

<h1>Porque tenemos que registar vuestra ubicacion?</h1>
<p>Si habilitas la ubicación precisa, podremos tener a tiempo completo la ubicacion
y usar tu ubicación precisa,dasdasdasdasdas como la información del GPS</p>
 

 
 </p>   
</body>
</html>